# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  # rpcURL: spdk json rpc target
  # targetType: nvme-rdma, nvme-tcp, iscsi
  # targetAddr: target service IP
  config.json: |-
    {
      "nodes": [
        {
          "name": "localhost",
          "rpcURL": "http://10.211.11.81:9009",
          "targetType": "nvme-tcp",
          "targetAddr": "10.211.11.81"
        }
      ]
    }
  node-config.json: |-
    {
      "name": "sma-controller-node",
      "subnqn": "nqn.2020-04.io.spdk.csi:",
      "transportAdrfam": "ipv4",
      "transportType": "tcp",
      "transportAddr": "10.211.11.81",
      "transportPort": "4421",
      "smaGrpcAddr":   "10.211.11.81:50051"
    }
# cfgRPCTimeoutSeconds: integer value of seconds
# cfgLvolClearMethod: none, unmap, write_zeroes
# cfgAddrFamily: IPv4, IPv6, IB, FC
  global-config.json: |-
    {
      "cfgRPCTimeoutSeconds": 20,
      "cfgLvolClearMethod": "unmap", 
      "cfgLvolThinProvision": true,
      "cfgNVMfSvcPort": "4420",
      "cfgISCSISvcPort": "3260",
      "cfgAllowAnyHost": true,
      "cfgAddrFamily": "IPv4" 
    }