# SPDX-License-Identifier: Apache-2.0
# Copyright (c) Arm Limited and Contributors
# Copyright (c) Intel Corporation
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: spdkcsi-cm
data:
  # rpcURL: spdk json rpc target
  # targetType: nvme-rdma, nvme-tcp, iscsi
  # targetAddr: target service IP
  config.json: |-
    {
      "nodes": [
        {
          "name": "localhost",
          "rpcURL": "http://127.0.0.1:9009",
          "targetType": "nvme-tcp",
          "targetAddr": "127.0.0.1"
        }
      ]
    }
  node-config.json: |-
    {
      "name": "localhost",
      "subnqn": "nqn.2020-04.io.spdk.csi:",
      "transportAdrfam": "ipv4",
      "transportType": "tcp",
      "transportAddr": "127.0.0.1",
      "transportPort": "4421",
      "smaGrpcAddr":   "127.0.0.1:50051"
    }
